### PR TITLE
RFC: Fix NRRD output axis order

### PR DESCRIPTION
**Pull request by ihnorton**
**NOTE: small change -- but please review very carefully and see note below**

| Before: | After: |
| ------- | ------ |
|image|image|

This turned out to be a little more involved than the pixel precision mismatch I [initially suspected](https://github.com/BRAINSia/BRAINSTools/commit/8693de7c6edec82f1639432c7a9826985ea7687b#commitcomment-25697933): NRRD output size axes appear to be swapped relative to ITK row-major array storage (and have been back at least [5 years or so](https://github.com/BRAINSia/BRAINSTools/commit/8cfbf80e241dd0a9cee8ef0040014a1c7fb97ee4)). In practice, this only matters when x and y axis dimensions are different -- as they happen to be in this particular dataset I was sent after a Slicer [forum post](https://discourse.slicer.org/t/dti-nifti-data-import-via-dwi-convert-module/1460/4).

Input nifti dimensions: 173 207 173 143
Output nrrd - before: `sizes: 207 173 173 143`
Output nrrd - after: `sizes: 173 207 173 143`

Apparently such an acquisition is relatively rare, though I'm still surprised this could have persisted for so long. As such, despite fixing read of this particular dataset, there's a chance I missed some underlying assumption elsewhere in the code. So, **please review carefully and run the test suite if possible before merging**. I'm not set up to run it myself right now, but if needed I can set it up to run on our cluster if it can't otherwise be run.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@ihnorton Thank you very much for doing this testing.  I will test as soon as I can.

**Comment by hjmjohnson** [comment]
Tests run and passed.

**Comment by hjmjohnson** [comment]
@ihnorton Thanks for your support.  Code confirmed.

**Comment by ihnorton** [comment]
Thanks!

**Pull request merged**
