### PR TITLE
Simplify buildsystem

### PR DESCRIPTION
**Pull request by jcfr**
This PR simplifies the buildsystem and should also address the issue reported by @lassoan:

```
In c:\D\S4R\Slicer-build\CMakeCache.txt there are just two configs:

CMAKE_CONFIGURATION_TYPES:STRING=Release;Debug

In the high-level Slicer build and in all external projects the list of configurations are complete (4 configs; except Python – but that’s a different matter, it’s fine; and Slicer-build).

I’ve only found one place in the Slicer build tree where somebody manipulates configuration types: in c:\D\S4R\BRAINSTools\CMakeLists.txt:

if(DEFINED CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_CONFIGURATION_TYPES "Release;Debug" CACHE STRING "" FORCE) # setting only two configuration types
endif()

I haven’t tested if this code changes the configurations available in Slicer but it’s quite likely. The configuration list override has been introduced by this commit:
https://github.com/BRAINSia/BRAINSTools/commit/831eab6bc8a77b7fb224c7dc23d89bb38a16d56c

Which later Jc tuned:
https://github.com/BRAINSia/BRAINSTools/commit/1a8e84b5b850a9f08338b23d80c18e459e0b01a1
```

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@jcfr THANK YOU!  I'll run one test, and then commit.

**Comment by hjmjohnson** [comment]
@jcfr All preliminary build testing came back successful.  THANK YOU.

**Comment by jcfr** [comment]
Great. Thanks for the quick feedback.

**Comment by jcfr** [comment]
Consider Slicer builds against ITK `v4.10.0rc2` from 2016-05-18, is it reasonable for Slicer to use BRAINSTools master ? 


Changes that would be included are the following:

```
$ git shortlog 16526a5..eab1460 --no-merges 
Alexander Leinoff (3):
      COMP: Dont build the BRAINSABC Module by default
      BUG: Fixes CMake Dependencies in DWIConvert
      ENH: Throw IO Exception when reading/writing invalid landmarks file

Ali Ghayoor (34):
      BUG: Fixed BRAINSFitTest_ROIBSpline by replacing the baseline
      ENH: Updated candidateRegionsThreshold value in BABC
      ENH: Make RC computation more stable
      BUG: Several modifications to identify bug in BCD
      BUG: Reliable computation of reflective correlation in BCD
      ENH: Add matlab companion to make a surface plot of metric
      ENH: print out CHM only in verbose mode
      ENH: Make BCD fail when we know results will be bad
      BUG: Move the physical origin to the center of the image
      BUG: Eyes ranges should be compared to aligned AC point
      BUG: Improved the input T1 test image by denoising
      BUG: Get MetaData dictionary from the reader output in BCD
      BUG: change the valid range for eye positions
      BUG: tuned valid range for eyes locations
      BUG: Generate ITK exception macro in the case of failure
      BUG: modify the threshold value for bad reflective correlation
      BUG: throw exception where needed
      BUG: Choose a reasonable search radius for mid-brain lmks
      BUG: new baselines for BCD search radius tests
      BUG: new baselines for BCD rescale intensity tests
      BUG: Fixed BCDTest_inputLandmarksEMSP
      BUG: Fixed twelve BCD test failures
      BUG: Fixed BCD forced lmks tests
      BUG: Fixed BCD lmks compare tests
      ENH: throw exception when error happens
      BUG: Fixed BRAINSTrimForeground test
      BUG: center of head mass must be passed to reflectionFunctor
      BUG: Fixed BRAINSAlignMSPTest
      ENH: RC computation is robust now, no need for repeated computation
      ENH: Consider a different threshold for RC metric
      ENH: Add correctionType to dtiestim in DWI pipeline
      ENH: Print a more informative error message in DWIConvert
      COMP: Added GTRACT as an option in cmake
      COMP: List the applications that need VTK in cmake build

Hans J. Johnson (70):
      PERF: Optimize cluster density usage
      BUG: Test for CenterOfROI had many bugs
      ENH: Make error checking robust for T1 image
      PERF: Allow running BCD with multiple cores
      ENH: Modernizing vcl_ to std::
      ENH: Update base code for fixing BAW features.
      COMP: Update for VTK 7.1 compilation
      ENH: Cleanup python code for snapshot writing.
      COMP: Remove compiler warning about unused variable.
      ENH: Update ANTs and ITK trying to resolve denoise issue
      ENH: Add ConvertBetweenFileFormats as a default build.
      ENH: RemoveVTKDependance.
      ENH: Allow building of BRAINSTools without VTK.
      COMP: Prefer _REQUIRES_VTK to BRAINSTools_REQUIRES_VTK
      COMP: Fix setting Mac OSX vars for build.
      ENH: Remove Compiler Warnings For clang c++11
      ENH: Const correctness and prefer initialization
      COMP: Compilation bug for mismatch signature.
      ENH: Update ITK to latest version.
      ENH: Hack hardcode to one file for speed.
      ENH: Added timing to computations.
      ENH: Instrument of heirarchial testing.
      ENH: Fine tune heuristic
      PERF: Use heirarcial heuristic for exhausitve search
      BUG: Replace std::__1::cout with std::cout
      ENH: Reorganize variables for readability.
      ENH: Update to new version of itkTestDriver*.inc files
      STYLE:  Put all old unused code at end of file.
      ENH: ITK, DCMTK, ANTs updated in hopes of addressing denoise empty images.
      ENH: Update version number of BRAINSTools.
      BUG: Update ANTS to fix Denoise.
      ENH: Update ITK and SlicerExecutionModel looking for linker warning resolution
      STYLE: Consolidate common typedef in one location
      COMP: Improve compilation by avoiding rebuilds of GenerateCLP
      COMP: KWSYS removed support for pre-C++98 in 2015
      COMP: Update to latest to remove compiler warnings
      COMP: CMP0063 Honor visibility properties for all target types
      ENH: Update ANTs to latest version.
      ENH: Update ITK version.
      PERF: Remove redundant assignment
      ENH: Remove shadowed typedefs
      ENH: Prefer const functions
      COMP: Address CPPCHECK warnings
      ENH: Allow specifying crash dump dir in config file.
      COMP: Incorrectly removed necessary function.
      COMP: Remove warnings about shadowed typedefs.
      ENH: Force T1 only processing for ANTS JointFusion.
      BUG: Only the first element was passing
      ENH: Update ITKv4.
      ENH: Change build for SlicerExecutionModel for visibility
      COMP: Conditionally turn off tests that require VTK
      COMP: Fix issues with SEM Hidden Symbols.
      DOC: Improve documentation for DWIConvert
      ENH: Fix regresion with respect to ITK 4.10
      ENH: Start of a test program for LinearRegression.
      BUG: Numerics for optimal averaging of images fixed
      ENH: Improve the unwrapping function
      ENH: Remove unnecessary outputs to reduce disk usage.
      ENH: Enable NIPYPE Provenance
      COMP: Remove incomplete test
      ENH: Partial additon of resampling code for all images
      ENH: Fine tune autoworkup for unwrapping and BABC candiate region thresholds.
      STYLE: Keep naming consistent with Slicer conventions.
      COMP: Silence compiler warnings
      ENH: Improve CSF and VB joint fusion results by cleanup
      BUG: Missing outputs when maxBiasOrder=0
      ENH: Improve true/false processing logic
      ENH: Use registration masks from template when available
      STYLE: Make the node name match the actual behavior
      ENH: Do not do BFC for BABC

Isaiah Norton (1):
      ENH: throw (overridable) error when attempting lossy NIFTI conversion.

Jean-Christophe Fillion-Robin (7):
      STYLE: Common.cmake: Group CMake include together and remove dead code.
      BUG: SuperBuild.cmake: Ensure calls to mark_as_superbuild are processed
      ENH: Superbuild.cmake: Simplify passing of build option to inner project.
      STYLE: CMakeLists.txt / Common.cmake: Remove commented code
      STYLE: Common.cmake: Remove unused variable ${PROJECT_NAME}_BUILD_FFTWF_SUPPORT
      BUG: Common.cmake: Do not force variable CTEST_CONFIGURATION_TYPE
      COMP: Update ExternalProjectDependency to support cache args with dbl quote

Juan Carlos Prieto (3):
      BUG: Linking error due to missing ITK libraries
      STYLE: Remove ITK version from find package
      Revert "STYLE: Remove ITK version from find package"

Regina Kim (10):
      ENH: ScreenShot script
      ENH: BCD user selected landmark option
      BUG: EMSP file error fix in BAW
      ENH: compute label volume
      ENH: Remove unused variables
      ENH: T2 is only excluded to Joint Fusion
      ENH: Stage5 Resgistration
      BUG: simpleITK BinaryThreshold
      BUG: save_state was not being used
      BUG: template and longitudinal pipeline fix
```

**Comment by hjmjohnson** [comment]
Yes,  Just be sure that BRAINSABC is not turned on (it has not been in the past).

 

Everything else in C++ should be backwards compatible for a few years ago for ITK.

 

Hans

 

 

--

**Comment by jcfr** [comment]
Roger that :+1: 

Have a good evening (if you are in EST timezone ..)

**Comment by ajjl** [comment]
@jcfr @hjmjohnson 

Hi. Thanks for your commits!

I've lost the ability to turn modules on and off through the superbuild. I think that this is related to your changes, I suspect this one, specifically the changes to SuperBuild.cmake: https://github.com/BRAINSia/BRAINSTools/pull/284/commits/5d27bb8fb730709c83ec35d7e20bbed49bbbc689
Here is an example of how to encounter the problem:
1) Create a new build folder. (ie. build from scratch)
2) Using ccmake, turn off a module that is normally on, for example BRAINSCostellationDetector
3) Build the project.
4) In the BRAINSTools project subfolder (${build_dir}/BRAINSTools-build), BRAINSConstellationDetector is still built. Looking at the cmake cache values from the subfolder ( Running "ccmake ." from BRAINSTools-build subfolder) shows that the module is turned on, even though I turned it off in the superbuild project.

Could you please re-review your changes and see if it looks like any of them could have caused this?

Thanks!

**Comment by hjmjohnson** [comment]
@ajjl I need to assign this task to you.  Currently I don't have time to investigate, and I know that JC is very very busy.  Please dig in and see if you can fix it.

Hans

**Comment by jcfr** [comment]
@ajjl Thanks for the detailed report.

Will investigate later today. We need to get this sorted out.

**Comment by ajjl** [comment]
I'll look into it.

**Comment by jcfr** [comment]
I found the problem ... this is caused by:
*  the fact the superbuild project and the inner project both have different names `SuperBuild_BRAINSTools` and `BRAINSTools`

and 

* the ExternalProjectDependency module internally default to checking for the variable `SuperBuild_BRAINSTools_SUPERBUILD` (instead of `BRAINSTools_SUPERBUILD`). See [here](https://github.com/commontk/Artichoke/blob/d453e329df962cf3d6def9028465237877f72e20/ExternalProjectDependency.cmake#L531-L535)

There are few options to move forward:

* [ ] (1) It is possible to explicitly specify the `SUPERBUILD_VAR` variable for each `ExternalProject_Include_Dependencies` call ... since ideally i would like to be able to share the `External_*` files between projects .. I would like to avoid this.

* [ ] (2) simplify BRAINSTools/CMakeLists.txt so that top-level and inner-project are named the same

* [ ] (3) Update `ExternalProject_Include_Dependencies` internals to check if a global variable named `EP_SUPERBUILD_VAR` is set. If set it would use it.

Ideally I would prefer (2), but  implementing (3) is also an option.

Let me know what you think

**Comment by hjmjohnson** [comment]
I definitely prefer the simplify approach

**Comment by jcfr** [comment]
> prefer the simplify approach

Great. Will keep that in mind for future refactoring

**Pull request merged**
