### PR TITLE
Free surfer breakout

### PR DESCRIPTION
**Pull request by dgellis90**
Should we add these workflows to BRAINSTools master? Or should we put them somewhere else? It would be nice to have them in the master of a git repository for the BrainkHack report.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Hopefully this can all go upstream into NIPYPE master.

Are the recon-all scripts part of the examples in nipype master?

For our report, we will point to BRAINSTools and we will make a link in the Autoworkup directory.

Hans

**Comment by dgellis90** [comment]
I'm not quite sure what you mean by the examples, but there is an example of running a recon-all workflow here: 
https://github.com/nipy/nipype/blob/master/examples/smri_freesurfer.py

**Comment by hjmjohnson** [comment]
That example does not use your pipeline.  

There should be a similar example to this that actually uses your pipeline.

**Comment by hjmjohnson** [comment]
@dgellis90 Hopefully a new version will replace this soon.

**Comment by dgellis90** [comment]
I'm working on adding the workflows to the nipype/master pull request as was requested.

**Comment by hjmjohnson** [comment]
Awesome!

Hans

**Pull request closed without merging**
