### PR TITLE
Add link to Slicer docs in DWIConvert README

### PR DESCRIPTION
**Pull request by ihnorton**
This is one of the top search results for `DWIConvert`, so probably useful to have a link.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@ihnorton Thanks.  I am trying to finalize a major update to DWIConvert that greatly improves compatibility with FSL file formats.

It should allow intercommunication with FSL.

I'm just finishing the testing today.

See: https://github.com/BRAINSia/BRAINSTools/tree/FixDWIConvert

Hans

**Comment by hjmjohnson** [comment]
@ihnorton FYI: I submitted and assigned to you a bug report for Slicer that is greatly slowing my ability to validate DWIConvert.

**Comment by ihnorton** [comment]
Ok, thanks for the heads-up. I'll take a look.

Btw, are you coming to the project week in January? I've been contemplating modifying the NRRD format to include b-values directly rather than the current scaling thing (which I'm not convinced is mathematically sound for multishell data, and has certainly not been implemented consistently).

**Comment by ihnorton** [comment]
(I responded on Mantis. pinging you here because the Mantis email notifications seem unreliable)

**Comment by hjmjohnson** [comment]
@ihnorton I am not coming to project week.  No funding.  

I'd be happy to help remotely though.  Changes to DWIConvert should be easy after the soon to be released changes.

Hans

**Pull request merged**
