### PR TITLE
COMP: Add header for missing std::isspace

### PR DESCRIPTION
**Pull request by phcerdan**
In windows std::isspace was not found without including <cctype>

### CODE REVIEW

**Comment by phcerdan** [comment]
@hjmjohnson @jcfr

**Comment by hjmjohnson** [comment]
@phcerdan Did you verify that that header exists on linux/mac?  If so, I'll merge.

**Comment by jcfr** [comment]
Lgtm :+1

Waiting for BRAINATools to be updated. Cherry pick in the Slicer fork with
prefix "[backport PR-424] " in the commit message title.

Thanks
Jc

**Comment by jcfr** [comment]
Thanks Hans

**Pull request merged**
