### PR TITLE
Fix mark as advanced option

### PR DESCRIPTION
**Pull request by hjmjohnson**
Fix propagating options from superbuild to project level.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@ihnorton  I think a fix is now available.  There is more clean-up that should occur, but I wanted to get this initial push to you ASAP.

**Comment by ihnorton** [comment]
Hi Hans, this worked perfectly. Thank you!

**Comment by hjmjohnson** [comment]
@ihnorton I did a lot of work this weekend to clean/modernize the build system for BRAINSTools.  I removed a lot of unnecessary redundancy.

Would you mind testing of this mornings latest master branch?  I think it should all work now.

Hans

**Comment by ihnorton** [comment]
I just built at 4256cbc -- though only DWIConvert and whatever else I didn't explicitly disable in the script in #379.

**Comment by ihnorton** [comment]
But I can run the full build and test suite if that would help. Do you know how much data that will be? This build is on a cluster and there are some space quotas I'm getting close to.

**Comment by hjmjohnson** [comment]
@ihnorton Thank you.  I just wanted to make sure that you used the latest superbuild construct.  That was all the information I need.

I've done complete builds on RHEL7 & Mac, and a build on Ubuntu is currently running.

**Pull request merged**
